/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AlreadyActivated = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Text,
  'fullName' : IDL.Text,
  'ghanaCardFrontKey' : ExternalBlob,
  'exportedAt' : IDL.Text,
  'extraInfo' : IDL.Opt(IDL.Text),
  'ghanaCardSelfieKey' : ExternalBlob,
  'accountNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'ghanaCardBackKey' : ExternalBlob,
});
export const DormantAccount = IDL.Record({
  'branch' : IDL.Text,
  'dateOfDormancy' : IDL.Text,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const FollowupRecord = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Text,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const OnlineReactivation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'activatedAt' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Text,
  'fullName' : IDL.Text,
  'ghanaCardFrontKey' : ExternalBlob,
  'extraInfo' : IDL.Opt(IDL.Text),
  'ghanaCardSelfieKey' : ExternalBlob,
  'accountNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'ghanaCardBackKey' : ExternalBlob,
});
export const PublicationAccount = IDL.Record({
  'branch' : IDL.Text,
  'dateOfDormancy' : IDL.Text,
  'accountName' : IDL.Text,
});
export const VerifyResult = IDL.Record({
  'found' : IDL.Bool,
  'accountName' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'accountNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearActivatedAccounts' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'clearFollowups' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'clearReactivations' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteActivatedAccounts' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteFollowups' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteReactivations' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'exportReactivation' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : AlreadyActivated, 'err' : IDL.Text })],
      [],
    ),
  'getActivatedAccounts' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(AlreadyActivated)],
      ['query'],
    ),
  'getActivatedData' : IDL.Func([], [IDL.Vec(AlreadyActivated)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDormantAccounts' : IDL.Func([], [IDL.Vec(DormantAccount)], ['query']),
  'getFollowups' : IDL.Func([], [IDL.Vec(FollowupRecord)], ['query']),
  'getFollowupsData' : IDL.Func([], [IDL.Vec(FollowupRecord)], ['query']),
  'getPendingReactivations' : IDL.Func(
      [],
      [IDL.Vec(OnlineReactivation)],
      ['query'],
    ),
  'getPendingReactivationsData' : IDL.Func(
      [],
      [IDL.Vec(OnlineReactivation)],
      ['query'],
    ),
  'getPublicationAccounts' : IDL.Func(
      [],
      [IDL.Vec(PublicationAccount)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'seedDormantAccounts' : IDL.Func(
      [IDL.Vec(DormantAccount)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitFollowup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitOnlineReactivation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifyAccount' : IDL.Func([IDL.Text], [VerifyResult], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AlreadyActivated = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Text,
    'fullName' : IDL.Text,
    'ghanaCardFrontKey' : ExternalBlob,
    'exportedAt' : IDL.Text,
    'extraInfo' : IDL.Opt(IDL.Text),
    'ghanaCardSelfieKey' : ExternalBlob,
    'accountNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'ghanaCardBackKey' : ExternalBlob,
  });
  const DormantAccount = IDL.Record({
    'branch' : IDL.Text,
    'dateOfDormancy' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const FollowupRecord = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const OnlineReactivation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'activatedAt' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Text,
    'fullName' : IDL.Text,
    'ghanaCardFrontKey' : ExternalBlob,
    'extraInfo' : IDL.Opt(IDL.Text),
    'ghanaCardSelfieKey' : ExternalBlob,
    'accountNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'ghanaCardBackKey' : ExternalBlob,
  });
  const PublicationAccount = IDL.Record({
    'branch' : IDL.Text,
    'dateOfDormancy' : IDL.Text,
    'accountName' : IDL.Text,
  });
  const VerifyResult = IDL.Record({
    'found' : IDL.Bool,
    'accountName' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'accountNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearActivatedAccounts' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'clearFollowups' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'clearReactivations' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteActivatedAccounts' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteFollowups' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteReactivations' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'exportReactivation' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : AlreadyActivated, 'err' : IDL.Text })],
        [],
      ),
    'getActivatedAccounts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(AlreadyActivated)],
        ['query'],
      ),
    'getActivatedData' : IDL.Func([], [IDL.Vec(AlreadyActivated)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDormantAccounts' : IDL.Func([], [IDL.Vec(DormantAccount)], ['query']),
    'getFollowups' : IDL.Func([], [IDL.Vec(FollowupRecord)], ['query']),
    'getFollowupsData' : IDL.Func([], [IDL.Vec(FollowupRecord)], ['query']),
    'getPendingReactivations' : IDL.Func(
        [],
        [IDL.Vec(OnlineReactivation)],
        ['query'],
      ),
    'getPendingReactivationsData' : IDL.Func(
        [],
        [IDL.Vec(OnlineReactivation)],
        ['query'],
      ),
    'getPublicationAccounts' : IDL.Func(
        [],
        [IDL.Vec(PublicationAccount)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'seedDormantAccounts' : IDL.Func(
        [IDL.Vec(DormantAccount)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitFollowup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitOnlineReactivation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifyAccount' : IDL.Func([IDL.Text], [VerifyResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };