/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlreadyActivated {
  'id' : bigint,
  'createdAt' : string,
  'fullName' : string,
  'ghanaCardFrontKey' : ExternalBlob,
  'exportedAt' : string,
  'extraInfo' : [] | [string],
  'ghanaCardSelfieKey' : ExternalBlob,
  'accountNumber' : string,
  'phoneNumber' : string,
  'ghanaCardBackKey' : ExternalBlob,
}
export interface DormantAccount {
  'branch' : string,
  'dateOfDormancy' : string,
  'accountName' : string,
  'accountNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface FollowupRecord {
  'id' : bigint,
  'createdAt' : string,
  'accountName' : string,
  'accountNumber' : string,
  'phoneNumber' : string,
}
export interface OnlineReactivation {
  'id' : bigint,
  'status' : string,
  'activatedAt' : [] | [string],
  'createdAt' : string,
  'fullName' : string,
  'ghanaCardFrontKey' : ExternalBlob,
  'extraInfo' : [] | [string],
  'ghanaCardSelfieKey' : ExternalBlob,
  'accountNumber' : string,
  'phoneNumber' : string,
  'ghanaCardBackKey' : ExternalBlob,
}
export interface PublicationAccount {
  'branch' : string,
  'dateOfDormancy' : string,
  'accountName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifyResult {
  'found' : boolean,
  'accountName' : [] | [string],
  'message' : string,
  'accountNumber' : [] | [string],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearActivatedAccounts' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'clearFollowups' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'clearReactivations' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteActivatedAccounts' : ActorMethod<
    [Array<bigint>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteFollowups' : ActorMethod<
    [Array<bigint>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteReactivations' : ActorMethod<
    [Array<bigint>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'exportReactivation' : ActorMethod<
    [bigint],
    { 'ok' : AlreadyActivated } |
      { 'err' : string }
  >,
  'getActivatedAccounts' : ActorMethod<
    [[] | [string]],
    Array<AlreadyActivated>
  >,
  'getActivatedData' : ActorMethod<[], Array<AlreadyActivated>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDormantAccounts' : ActorMethod<[], Array<DormantAccount>>,
  'getFollowups' : ActorMethod<[], Array<FollowupRecord>>,
  'getFollowupsData' : ActorMethod<[], Array<FollowupRecord>>,
  'getPendingReactivations' : ActorMethod<[], Array<OnlineReactivation>>,
  'getPendingReactivationsData' : ActorMethod<[], Array<OnlineReactivation>>,
  'getPublicationAccounts' : ActorMethod<[], Array<PublicationAccount>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'seedDormantAccounts' : ActorMethod<
    [Array<DormantAccount>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitFollowup' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitOnlineReactivation' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifyAccount' : ActorMethod<[string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];