/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VerifyResult {
    found: boolean;
    accountName?: string;
    message: string;
    accountNumber?: string;
}
export interface PublicationAccount {
    branch: string;
    dateOfDormancy: string;
    accountName: string;
}
export interface DormantAccount {
    branch: string;
    dateOfDormancy: string;
    accountName: string;
    accountNumber: string;
}
export interface AlreadyActivated {
    id: bigint;
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: ExternalBlob;
    exportedAt: string;
    extraInfo?: string;
    ghanaCardSelfieKey: ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: ExternalBlob;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FollowupRecord {
    id: bigint;
    createdAt: string;
    accountName: string;
    accountNumber: string;
    phoneNumber: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OnlineReactivation {
    id: bigint;
    status: string;
    activatedAt?: string;
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: ExternalBlob;
    extraInfo?: string;
    ghanaCardSelfieKey: ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: ExternalBlob;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearActivatedAccounts(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearFollowups(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearReactivations(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteActivatedAccounts(ids: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteFollowups(ids: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteReactivations(ids: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    exportReactivation(id: bigint): Promise<{
        __kind__: "ok";
        ok: AlreadyActivated;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActivatedAccounts(search: string | null): Promise<Array<AlreadyActivated>>;
    getActivatedData(): Promise<Array<AlreadyActivated>>;
    getCallerUserRole(): Promise<UserRole>;
    getDormantAccounts(): Promise<Array<DormantAccount>>;
    getFollowups(): Promise<Array<FollowupRecord>>;
    getFollowupsData(): Promise<Array<FollowupRecord>>;
    getPendingReactivations(): Promise<Array<OnlineReactivation>>;
    getPendingReactivationsData(): Promise<Array<OnlineReactivation>>;
    getPublicationAccounts(): Promise<Array<PublicationAccount>>;
    isCallerAdmin(): Promise<boolean>;
    seedDormantAccounts(accounts: Array<DormantAccount>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitFollowup(accountNumber: string, phoneNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitOnlineReactivation(fullName: string, phoneNumber: string, accountNumber: string, extraInfo: string | null, ghanaCardFrontKey: ExternalBlob, ghanaCardBackKey: ExternalBlob, ghanaCardSelfieKey: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyAccount(accountNumber: string): Promise<VerifyResult>;
}
import type { AlreadyActivated as _AlreadyActivated, ExternalBlob as _ExternalBlob, OnlineReactivation as _OnlineReactivation, UserRole as _UserRole, VerifyResult as _VerifyResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearActivatedAccounts(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clearActivatedAccounts();
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearActivatedAccounts();
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearFollowups(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clearFollowups();
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearFollowups();
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearReactivations(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clearReactivations();
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearReactivations();
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteActivatedAccounts(arg0: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivatedAccounts(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivatedAccounts(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFollowups(arg0: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowups(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowups(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReactivations(arg0: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReactivations(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReactivations(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportReactivation(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: AlreadyActivated;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.exportReactivation(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportReactivation(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivatedAccounts(arg0: string | null): Promise<Array<AlreadyActivated>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivatedAccounts(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivatedAccounts(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivatedData(): Promise<Array<AlreadyActivated>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivatedData();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivatedData();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDormantAccounts(): Promise<Array<DormantAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDormantAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDormantAccounts();
            return result;
        }
    }
    async getFollowups(): Promise<Array<FollowupRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowups();
            return result;
        }
    }
    async getFollowupsData(): Promise<Array<FollowupRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowupsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowupsData();
            return result;
        }
    }
    async getPendingReactivations(): Promise<Array<OnlineReactivation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReactivations();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReactivations();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingReactivationsData(): Promise<Array<OnlineReactivation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReactivationsData();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReactivationsData();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicationAccounts(): Promise<Array<PublicationAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicationAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicationAccounts();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async seedDormantAccounts(arg0: Array<DormantAccount>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDormantAccounts(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDormantAccounts(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFollowup(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFollowup(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFollowup(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitOnlineReactivation(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: ExternalBlob, arg5: ExternalBlob, arg6: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOnlineReactivation(arg0, arg1, arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg6));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOnlineReactivation(arg0, arg1, arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg6));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAccount(arg0: string): Promise<VerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAccount(arg0);
                return from_candid_VerifyResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAccount(arg0);
            return from_candid_VerifyResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_AlreadyActivated_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlreadyActivated): Promise<AlreadyActivated> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_OnlineReactivation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnlineReactivation): Promise<OnlineReactivation> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: _ExternalBlob;
    exportedAt: string;
    extraInfo: [] | [string];
    ghanaCardSelfieKey: _ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: _ExternalBlob;
}): Promise<{
    id: bigint;
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: ExternalBlob;
    exportedAt: string;
    extraInfo?: string;
    ghanaCardSelfieKey: ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: ExternalBlob;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        fullName: value.fullName,
        ghanaCardFrontKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardFrontKey),
        exportedAt: value.exportedAt,
        extraInfo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.extraInfo)),
        ghanaCardSelfieKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardSelfieKey),
        accountNumber: value.accountNumber,
        phoneNumber: value.phoneNumber,
        ghanaCardBackKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardBackKey)
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    activatedAt: [] | [string];
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: _ExternalBlob;
    extraInfo: [] | [string];
    ghanaCardSelfieKey: _ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: _ExternalBlob;
}): Promise<{
    id: bigint;
    status: string;
    activatedAt?: string;
    createdAt: string;
    fullName: string;
    ghanaCardFrontKey: ExternalBlob;
    extraInfo?: string;
    ghanaCardSelfieKey: ExternalBlob;
    accountNumber: string;
    phoneNumber: string;
    ghanaCardBackKey: ExternalBlob;
}> {
    return {
        id: value.id,
        status: value.status,
        activatedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.activatedAt)),
        createdAt: value.createdAt,
        fullName: value.fullName,
        ghanaCardFrontKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardFrontKey),
        extraInfo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.extraInfo)),
        ghanaCardSelfieKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardSelfieKey),
        accountNumber: value.accountNumber,
        phoneNumber: value.phoneNumber,
        ghanaCardBackKey: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.ghanaCardBackKey)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: boolean;
    accountName: [] | [string];
    message: string;
    accountNumber: [] | [string];
}): {
    found: boolean;
    accountName?: string;
    message: string;
    accountNumber?: string;
} {
    return {
        found: value.found,
        accountName: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.accountName)),
        message: value.message,
        accountNumber: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.accountNumber))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AlreadyActivated;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: AlreadyActivated;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_AlreadyActivated_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlreadyActivated>): Promise<Array<AlreadyActivated>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AlreadyActivated_n12(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OnlineReactivation>): Promise<Array<OnlineReactivation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OnlineReactivation_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
